### ISSUE TITLE
[Feature] - 6.1 토글바를 이용해 라이트모드, 다크모드를 바꿀 수 있다.

### ISSUE THREAD

**Issue by demian-m00n** [boostcampwm-2024/web17-boostproject#100]
# Description

토글바를 이용해 라이트모드, 다크모드를 바꿀 수 있다.

# To-do
- [ ] 라이트모드, 다크모드를 전환할 수 있는 토글 UI를 제공한다.
- [ ] 토글 동작을 통해 라이트모드, 다크모드를 전환한다.
- [ ] 전환될 때 상태를 서버에 전송한다.

# ETC
