### ISSUE TITLE
[Feature] - 3.1 개별 주식을 클릭하면 개별 주식창으로 넘어가는 UI를 제공한다.

### ISSUE THREAD

**Issue by demian-m00n** [boostcampwm-2024/web17-boostproject#123]
# Description

개별 주식을 클릭하면 개별 주식창으로 넘어간다.

# To-do

FE
- [x] 개별 주식에 대한 링크 생성
- [x] 링크 이동에 대한 컴포넌트 구현  
- [x] 개별 주식 선택시 조회수 증가

# ETC
