### ISSUE TITLE
[Feature] - 3.2 서버로 부터 제공받은 실시간 데이터를 TradingView를 통해 사용자에게 보여준다.

### ISSUE THREAD

**Issue by demian-m00n** [boostcampwm-2024/web17-boostproject#125]
# Description

서버로 부터 제공받은 실시간 데이터를 TradingView를 통해 사용자에게 보여준다.

# To-do

- [ ] FE
   - [x] 서버로부터 데이터를 받아 그려낸다.
   - [ ] 1분 주기로 서버와 지속적으로 데이터를 받아 그래프를 갱신한다.
   - [x]  사용자가 일,월,년을 클릭할 때의 상태값으로 저장해서 바뀔 때마다 서버에 데이터를 재요청한다.
 
# ETC
