### ISSUE TITLE
[Feature] - 커스텀 exception 구현 및 exception filter 설정

### ISSUE THREAD

**Issue by xjfcnfw3** [boostcampwm-2024/web17-boostproject#132]
# Description
- 커스텀 exception 구현 및 exception filter 구현
# To-do
- [ ] 커스텀 exception 구현
- [ ] exception filter 구현
- [ ] 커스텀 exception을 제외한 exception 필터 구현(logger 사용)

# ETC
