### ISSUE TITLE
[Feature] - 2.1 로그인한 사람들이 주식 채팅방에 참여할 수 있다.

### ISSUE THREAD

**Issue by xjfcnfw3** [boostcampwm-2024/web17-boostproject#152]
# Description
로그인한 사람들이 주식 채팅방에 참여할 수 있다.
# To-do
- [x] 채팅 도메인 구현
- [x] 종목별 채팅방 진행
- [x] 인증된 사용자가 채팅을 입력
- [x] 채팅 데이터를 DB에 저장

# ETC
