### ISSUE TITLE
[Feature] - 3.2 주식의 현재가, 변동률, EPS 등을 보여주는 UI를 제공한다.

### ISSUE THREAD

**Issue by baegyeong** [boostcampwm-2024/web17-boostproject#24]
# Description

개별 주식의 각각의 정보에 마우스를 호버링하면 툴팁을 제공한다.

# TODO

- [ ] 정보마다 도움말 아이콘 추가
- [ ] 도움말 아이콘 호버링 시 툴팁 렌더링
- [ ] 현재가, 거래량, 변동률, 52주 최고/최저가, 시가총액, PER, EPS를 서버로부터 제공받아 화면에 띄운다.

# ETC
