### ISSUE TITLE
[Feature] - 시간(일,주,월,년) 단위로 그래프를 그릴 수 있다.

### ISSUE THREAD

**Issue by baegyeong** [boostcampwm-2024/web17-boostproject#245]
# Description

주식에 관한 정보를 시간(일,주,월,년) 단위로 그래프를 그릴 수 있다.

# To-do

- [x] 시간 단위 상태 관리
- [x] 시간에 따른 api 호출
- [x] 시간에 따른 그래프 렌더링

# ETC
