### ISSUE TITLE
[1.1] - 사용자가 원하는 한국 KOSPI / KOSDAQ 주식의 가격이 요구 조건에 도달하면 알림이 온다.

### ISSUE THREAD

**Issue by demian-m00n** [boostcampwm-2024/web17-boostproject#25]
# Description

사용자가 원하는 한국 KOSPI / KOSDAQ 주식의 가격이 요구 조건에 도달하면 알림이 온다.

# To-do
- [ ] 사용자는 특정 템플릿의 이메일을 받는다. (#4)
- [ ] 주식이 설정한 요구 조건에 도달하면 알림이 사용자에게 도달한다.
- [ ] DB에 요구 조건이 맞는 알림을 확인한다.

# ETC
