### ISSUE TITLE
[BUG] - stock detail 타입 가드, PK 키 아닌 값에 unique 적용, period 수정

### ISSUE THREAD

**Issue by swkim12345** [boostcampwm-2024/web17-boostproject#250]
# To-do

- [x] 현재 타입가드는 되어 있지만, 제대로  적용되지 않는 문제가 있음.
- [x] 추가적인 문제 발생 방지를 위해 pk가 아닌 unique 속성에 unique 적용
- [x] period값으로 받아오는 것을 에러 상황일 때 다시 부르는 것으로 수정함.

# ETC
