### ISSUE TITLE
[1.2] - 사용자가 알림의 요구 조건을 설정하고 등록한다.

### ISSUE THREAD

**Issue by demian-m00n** [boostcampwm-2024/web17-boostproject#26]
# Description

사용자가 알림의 요구 조건을 설정하고 등록한다.

# To-do
- [ ] 사용자는 원하는 가격, 변동률, 지표를 입력 받도록한다. (#6)
- [ ] 주식 그래프가 보이는 개별 페이지에서 선택할 수 있다. (#8)
- [ ] 기한을 정할 수 있다.
- [ ] 주식의 특정 가격을 원화로 결정할 수 있다.
- [ ] 특정 주식을 선택할 수 있다.
- [ ] (후순위) notice 알람이 추가될 때 이메일과 notice 중에서 선택할 수 있다.
- [ ] 특정 주식, 특정 가격, 지표, 기한을 받는 엔드포인트를 만든다.
- [ ] 이와 관련된 ERD를 제작한다. - alarm (#12)

# ETC
