### ISSUE TITLE
[Refactoring] - 웹소켓 리팩토링

### ISSUE THREAD

**Issue by swkim12345** [boostcampwm-2024/web17-boostproject#284]
# Description

- websocket에는 현재 키값을 하나만 사용중에 있다.
- 이를 확장할 수 있는 구조로 변경하고, 외부로 노출되는 함수에는 변화가 없이 유지하자.

# To-do

- [x] 웹소켓 다중값 허용
- [x]  gateway injectable 추가, mutex 추가
- [x]  외부 노출 함수은 변화 없이 유지

# ETC
