### ISSUE TITLE
[BUG] - 자잘한 UI 에러 수정

### ISSUE THREAD

**Issue by baegyeong** [boostcampwm-2024/web17-boostproject#295]
# Description

자잘한 UI를 에러를 수정한다.

# To-do

- [x] 사이드바가 어떠한 화면에 가려지는 문제
- [x] 주주 문구 변경
- [x] 채팅 블러 처리 방법 수정
- [x] 반응형 개선
- [x] 주식 탭 임의로 삼성전자 연결
- [x] 게스트 로그인 성공시 메인으로 이동
- [x] 마이페이지에서 소유주식 삭제 시 이벤트 버블링 되는 문제

# ETC
