### ISSUE TITLE
[Feature] - 유저 멘션 결과 변경 및 멘션 입력 변경

### ISSUE THREAD

**Issue by xjfcnfw3** [boostcampwm-2024/web17-boostproject#308]
# Description
기존에는 유저 멘션 결과를 id 값을 통해 전달하도록 했지만, 보안상 이유로 닉네임 서브네임 조합으로 변경
추가로 다크모드 조회 방식도 변경
# To-do
- [ ] 유저 검색 결과를 닉네임 서브네임으로 변환 
- [ ] 다크모드 조회를 쿠키로 통해 진행
- [ ] 멘션 진행을 닉네임, 서브네임으로 진행

# ETC
