### ISSUE TITLE
[1.4] - 사용자는 등록한 알림을 관리할 수 있다.

### ISSUE THREAD

**Issue by demian-m00n** [boostcampwm-2024/web17-boostproject#31]
# Description

사용자는 등록한 알림을 관리할 수 있다.

# To-do
- [ ] 사용자는 특정 페이지에서 등록한 알림을 확인할 수 있다. (#9)
- [ ] 사용자는 특정 주식에서 주식 종류를 제외한 나머지(가격, 기한, 변동률 등)을 변경할 수 있다. (#13)
- [ ] 서버에서 푸시 알림 차단 정보를 저장한다.
- [ ] 사용자는 등록한 알림에 대해 삭제할 수 있다.
- [ ] 마이 페이지에서 푸시 알림 버튼을 누를 수 있다.
- [ ] 사용자는 알림 주기를 설정할 수 있다.
- [ ] (후순위) 특정 주식의 알림을 등록할 때 주식을 보유할 수 있는지 확인하는 모달창과 함께 자산 등록 기능을 연동할 수 있다.
- [ ] 이메일에 푸시 알림 차단 링크를 전달한다.
- [ ] 알림 횟수를 설정할 수 있다.

# ETC
