### ISSUE TITLE
[Refactoring] - 알림 구현 보강, 명세 작성

### ISSUE THREAD

**Issue by swkim12345** [boostcampwm-2024/web17-boostproject#314]
# Description
- 알림 구현 내에서 피드백 받은 부분을 구현하고, 테스트코드가 없는 것을 이메일 고려 없이 구현한다.

# To-do
- [ ] #313 피드백 내용 반영
- [x] web push 명세 작성
- [ ] 테스트 코드 - ts-mockito로 작성

# ETC
