### ISSUE TITLE
[Story] - 성능 테스트 및 개선 이후 트래킹

### ISSUE THREAD

**Issue by swkim12345** [boostcampwm-2024/web17-boostproject#334]
# Description

- 현재 성능적으로 개선할 부분이 있다. 성능 개선 전, 개선 후 성능 테스트 후 전반적으로 얼마나 향상되었는 지 서술이 필요하다.

# To-do

- [x] 성능 테스트 프로그램 선정
- [x] 로컬 캐시 적용
- [ ] pm2 적용
- [ ] (후순위)캐싱할 수 있는 파일 cdn 적용

# ETC
