### ISSUE TITLE
[Feature] - 큐 요청 횟수 제한

### ISSUE THREAD

**Issue by xjfcnfw3** [boostcampwm-2024/web17-boostproject#358]
# Description
큐 내에 무한정으로 에러가 발생하게 된다면, 다른 요청이 진행할 수 없는 문제와 메모리 누수 현상도 발생할 여지가 있다. 이를 해결하고자 큐 사용횟수를 제한하여 진행하도록 함
# To-do

- [x] 큐 요청 횟수 제한
- [x] 주, 월, 년 누락된 차트 데이터가 갱신되지 않는 문제 해결
- [x] 누락된 차트 수집 허용 시간 추가

# ETC
