### ISSUE TITLE
[BUG] - eslint, string리턴 수정, swagger 성공하게 조건 변경

### ISSUE THREAD

**Issue by swkim12345** [boostcampwm-2024/web17-boostproject#369]
# alarm module

# To-do

- [ ] eslint 안 맞는 거 수정
- [ ] string 리턴 수정
- [ ] swagger 성공하게 조건 변경

# ETC
