### ISSUE TITLE
[Feature] - 6.3 사용자는 상위 20개의 주식의 차트와 가격을 볼 수 있다.

### ISSUE THREAD

**Issue by baegyeong** [boostcampwm-2024/web17-boostproject#40]
# Description

사용자는 상위 20개의 주식의 차트와 가격을 볼 수 있다.

# To-do
- FE
  - [x] 상위 20개 순위를 보여준 테이블 UI 구성
  - [x] 상위 20개 데이터 요청
  - [x] 상위 20개 데이터 렌더링
  - [x] 가격 상승/하락 선택 가능
  - [x] 가격 상승/하락 선택에 따라 데이터 요청 

# ETC
